export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const LOAD_INGREDIENT = 'LOAD_INGREDIENT'
export const GET_AUTH = 'GET_AUTH'
export const LOGOUT = "LOGOUT"
export const GET_LOCAL_AUTH = "GET_LOCAL_AUTH"